version: '3.9'
services:
    itrade-dongs-api-php:
        image: itrade-dongs-api-php
        build:
            context: .
            dockerfile: ./docker-conf/webserver/Dockerfile
        ports:
            - 8001:8080
    itrade-dongs-mysql:
        image: itrade-dongs-mysql
        build:
            context: .
            dockerfile: ./docker-conf/mysql/Dockerfile
        cap_add:
            - SYS_NICE
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: sFg$8d7QW@sd
            MYSQL_DATABASE: u631028490_itrade
        ports:
            - 8002:3306
        volumes:
            - ./docker-volumes/mysql-datavolume:/var/lib/mysql
            - ./docker-volumes/mysql-filevolume:/filevolume
            - ./docker-conf/mysql/init:/docker-entrypoint-initdb.d/:ro
